# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monservice', '0005_auto_20171023_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('access_group_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AccessUrlGroup',
            fields=[
                ('access_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_url_set', models.CharField(max_length=128)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_url_group_fk', to='rentservice.AccessGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('appointment_detail_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('box_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserGroup',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_token', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_group_fk', to='rentservice.AccessGroup')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseInfo',
            fields=[
                ('enterprise_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('enterprise_name', models.CharField(max_length=128)),
                ('enterprise_tele', models.CharField(max_length=32)),
                ('register_time', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('user_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=48)),
                ('user_password', models.CharField(max_length=32)),
                ('register_time', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_service_admin_enterprise_info_fk', to='rentservice.EnterpriseInfo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_user_fk', to='rentservice.AuthUserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAdminOperationRecords',
            fields=[
                ('record_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RentalAdminOperationType',
            fields=[
                ('type_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('operation_name', models.CharField(default='default operation', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RentalServiceAdmin',
            fields=[
                ('user_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=48)),
                ('user_password', models.CharField(max_length=32)),
                ('register_time', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_service_admin_fk', to='rentservice.AuthUserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserAppointment',
            fields=[
                ('appointment_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('appointment_time', models.CharField(max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment_fk', to='rentservice.EnterpriseUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserLeaseInfo',
            fields=[
                ('user_lease_info_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('lease_start_time', models.CharField(max_length=64)),
                ('lease_end_time', models.CharField(max_length=64)),
                ('rent', models.BigIntegerField(default=0)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lease_info_box_info_fk', to='monservice.BoxInfo')),
                ('lease_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lease_info_rental_service_admin_fk', to='rentservice.RentalServiceAdmin')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lease_info_site_info_fk', to='monservice.SiteInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lease_info_enterprise_user_fk', to='rentservice.EnterpriseUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRentMonth',
            fields=[
                ('user_rent_month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(default='20171101', max_length=16)),
                ('rent', models.BigIntegerField(default=0)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent_month_enterprise_info_fk', to='rentservice.EnterpriseInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent_month_enterprise_user_fk', to='rentservice.EnterpriseUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRentYear',
            fields=[
                ('user_rent_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default='2017', max_length=8)),
                ('rent', models.BigIntegerField(default=0)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent_year_enterprise_info_fk', to='rentservice.EnterpriseInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rent_year_enterprise_user_fk', to='rentservice.EnterpriseUser')),
            ],
        ),
        migrations.AddField(
            model_name='rentaladminoperationrecords',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_admin_operation_record_rental_admin_id_fk', to='rentservice.RentalServiceAdmin'),
        ),
        migrations.AddField(
            model_name='rentaladminoperationrecords',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_admin_operation_record_oper_type_fk', to='rentservice.RentalAdminOperationType'),
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_detail_user_appointment_fk', to='rentservice.UserAppointment'),
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='box_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_detail_box_type_fk', to='monservice.BoxTypeInfo'),
        ),
    ]
